import React from 'react';
import './FoundersPage.css';
import founderImage from '../assets/CentralPerson.jpg'; // Replace with actual image path

const FoundersPage = () => {
  return (
    <div className="founders-page-container">
      <h1 className="founders-page-heading">Dr. Moumita Nandy</h1>
      <div className="founders-page-content">
        <img src={founderImage} alt="Dr. Moumita Nandy" className="founders-page-image" />
        <p>Everyone deserves a space to heal, recharge, and feel empowered to tell their story. I help people to explore their past, learn about the present, and cultivate a more authentic future.</p>
        <p>I work to create a safe, healing environment for individuals of diverse racial and cultural backgrounds, sexual orientations, gender identities, religion, and body sizes.</p>
        <p>Therapy is the art of mining gold from the spirit and the science of transformative conversation.</p>
        <ul>
          <li>Narrative Therapist, mentored by David Epston, the father of Narrative Therapy.</li>
          <li>Gottman Trained Marital Therapist</li>
          <li>Anger Management Treatment Provider</li>
          <li>Spiritually Based Psychotherapist</li>
          <li>Certified Cognitive Behavioural Therapist</li>
          <li>Trauma Treatment Specialist with experience of over 10 years.</li>
          <li>A Certified Narrative practitioner (from)</li>
        </ul>
        <p>I am a psychotherapist who helps people find mental health through a holistic mind-body-spirit approach. Over time I evolved my clinical training to include a social justice approach blended with contemplative practices. My hope for each client is they discover their own healing power as I support them on their journey towards health and well-being.</p>
        <p>I have over 12 years of experience in dealing with individuals, couples, and teens. My area of focus is trauma, narcissistic abuse, anxiety, depression, relationships, adoption, navigating life transitions, daily living issues, and anything else that you would like to heal, grow from or explore! I believe we can all heal and learn to work through our traumas.</p>
        <p>My goal is to assist everyone in their journey towards healing, no matter what your reason for coming to therapy. My practice is inclusive and sensitive.</p>
        <p>My philosophy of therapy is very personal, collaborative and a unique blend of many techniques, helping us to examine the bigger picture of your life.</p>
        <p>Mental health issues have been a silent battle for many because of the whole stigma around it and also due to the immense fear of labelling, which has often discouraged people to share their emotions, thoughts, and feelings. Looking towards the stigma that has always been associated with mental health, made me enter the field and since then I have never looked back. Working as a mental health practitioner has really been my calling and my passion made me associate with places like Cancer Institute, Chennai and Tata Cancer Institute, Kolkata. I genuinely feel that awareness is the gateway to understanding and self-actualisation and as people realise that mental well-being would be more accessible and proliferative. The aim and motto I work through is to make the patients realise of the sources of their issues and not their triggers because when you understand the source, you are more in touch with your feelings and emotions. I teach them effective coping techniques which has helped them change their behavioural patterns and this has proven to be 87% effective and has seen a significant improvement in their mental health and overall well-being. I have always enjoyed interacting with each patient and learning how I can help them face daily challenges. Every day, in every possible way, I help people stand up to stigma. I strongly believe in this and for me it is very important to provide a welcoming and positive environment, away from labels towards a holistic approach to betterment.</p>
        <p>My forte is providing psychological aid in a clinical setup. I take every opportunity to educate people and encourage them to share their struggles with mental illness. It doesn't matter where you are from, if you overhear a conversation or a rude remark being made about mental illness, or anything regarding a similar subject, always try to use that as a learning opportunity and gently intervene and kindly express how this makes you feel, and how we need to stop this because it only adds to the stigma. I find that when people understand the true facts of what a mental illness is, they will think twice about making comments. I also remind them that they wouldn't make fun of someone with diabetes, heart disease, or cancer. I offer free hugs to people and sit right there and talk with them about their lives. I do this in public at times, and model compassion for others. Since most of our population is struggling with mental illness, the simple act of showing affection can make their day and also remind others of something so easily forgotten: the humanity of those who are suffering.</p>
        <p>Most people who live with mental illness have, at some point, been blamed for their condition. They have been called names. Their symptoms have been referred to as “a phase” or something they can control “if they only tried.” They have been illegally discriminated against, with no justice. This is the unwieldy power that stigma holds. Stigma causes people to feel ashamed for something that is out of their control. Worst of all, stigma prevents people from seeking the help they need. Stigma is an unacceptable addition to their pain and their already heavy burden. And while stigma has reduced in recent years, the pace of progress has not been quick enough.</p>
        <p>My mission is to destigmatize mental health and make people understand that they are not different and there is nothing to be ashamed of and it’s their right to dispose of their pain and harbour in positive thoughts and feelings about themselves.</p>
        <p>One of the greatest challenges I have faced as a mental health practices is how to attract more patients and build a stronger client base through healthcare marketing. Marketing mental health services starts with creating a marketing plan. Building a solid mental health marketing plan can be a daunting task for many mental health experts. I have often wished that I had more training in marketing management or social media marketing before starting my practices. Understanding how healthcare marketing works is even more important today, when savvy online consumers routinely tap into digital resources where they can find a variety of mental health service provider options in their area.</p>
        
        <p>Mental health and wellness start-ups are not only capitalising on the opportunity by intervening when people most need their help, but also have found revenue and user growth to establish themselves as a presence in the market. Many industry experts also believe that the demand for such service is only going to increase given the uncertainty caused due to Covid-19, and the rise in anxiety-related disorder, depression, work-related stress, is only going to increase, and the need for professional service becomes critical. While pandemic has come as a blessing in disguise for mental health space, it has removed the social stigma and medium from the equation — you don’t have to physically go somewhere to get therapy done, everything can happen with a click of a button. For decades, the mental wellness space was associated only with NGOs and ‘not for profits.’ This is slowly changing now as private players, investors are entering into this space, but there’s still a long way to go, as the industry is still in the nascent stages in the country. Overall, this illustrates the importance of mental health more than ever and urges the need for quality mental health care in the country as more and more players enter this space. Most importantly, this is essential for the country’s long-term growth, wellbeing and economy since the wellbeing of people contributes greatly to economic and social productivity. Our app is aiming for the above discussed.</p>
        <p>For me, the concept of mental health doesn’t end with diagnosis and recovery. It’s vital to focus on maintenance as well. We all have certain levels of anxiety within us and to manage those levels, we need to focus on the source rather than the trigger. So when we ask a loved one what they’re feeling, people will be more acceptable towards their mental health and that of others. My goal is to make mental health more accessible. I am someone who would like to address the issues not only at a symptomatic manner but focus on the asymptomatic details. Uncovering the underlying beliefs and emotions within humans is important, and my way of working includes a holistic approach to betterment.</p>
        <p>Pandemic was a huge transition for everyone, a paradigm shift. Like any other transition, it brought in uncertainty, lack of vision, unpredictability, and lack of insight. This furthermore led to multiple associations which catapulted anxiety and fear. The best thing is to pace yourself during a transition. “Slow down to speed up.” You’ve heard this before, right? And, “You don’t know what you don’t know.” These familiar phrases are often used in life which will help to create a homeostasis.</p>
        <p>Transition management does not mean that an immediate return to normal will be possible. Instead, the transition process will take place in accordance with a phased approach whereby society, systems and services are gradually re-opened, potentially in new forms. Each phase may involve adjustments to restrictions and potential re-employment of previous stricter measures. During this complex process, if people think that they are or soon will be returning to normal, their actions may hasten the onset of a psychological breakdown, so scheduling and creating smaller goals will help them feel more secured and help in better adaptation towards the new lifestyle.</p>
      </div>
    </div>
  );
};

export default FoundersPage;
