import React from 'react';
import './OverAllInfo.css';

const OverallInfo = () => {
  return (
    <div className="overall-info-container">
      <h1 className="overall-info-heading">Haus Of Calm</h1>
      <div className="overall-info-content">
        <h2>Mission Statement</h2>
        <p>Our mission is to create a vibrant and inclusive community space dedicated to nurturing the mental, emotional, and physical well-being of every individual who walks through our doors. We strive to provide a sanctuary where people can find solace, strength, and connection as they navigate life’s challenges. Through a comprehensive array of services, including therapeutic practices, wellness workshops, support groups, and creative expression, we empower individuals to embark on a journey of self-discovery and healing.</p>
        <p>We are committed to cultivating a culture of empathy and mutual support, where members of our community are encouraged to share their stories, listen to others, and build meaningful relationships based on trust and understanding. Our holistic approach integrates traditional and alternative therapies, recognizing the interconnectedness of mind, body, and spirit. By offering personalized care and fostering a sense of belonging, we aim to help individuals develop the resilience and skills needed to thrive in all areas of their lives.</p>
        <p>We believe that healing and growth are deeply personal yet profoundly communal experiences. Therefore, our mission is to create a space where each person feels empowered to take charge of their well-being, while also contributing to the well-being of others. Together, we aspire to build a supportive and compassionate community that stands as a testament to the transformative power of connection and care.</p>

        <h2>Vision Statement</h2>
        <p>We envision a future where our wellness space serves as a cornerstone of the community, a place where individuals from diverse backgrounds come together to share in the journey of holistic well-being. In this future, mental health and wellness are no longer stigmatized but celebrated as essential components of a healthy and fulfilling life. Our vision is to become a hub of innovation in mental health and wellness, continually evolving to meet the changing needs of our community while staying rooted in our core values of compassion, inclusivity, and empowerment.</p>
        <p>Our space will be a sanctuary where people can escape the pressures of everyday life and immerse themselves in a supportive environment that fosters healing and growth. We will offer a wide range of programs designed to address the unique needs of our community, from mindfulness and meditation sessions to art therapy, nutrition counseling, and movement classes. By providing access to diverse wellness practices and expert guidance, we aim to help individuals explore new ways of caring for themselves and each other.</p>
        <p>In the long term, we aspire to create a ripple effect of positive change, extending beyond the walls of our wellness space. We believe that by fostering a community where people feel safe, valued, and supported, we can inspire others to prioritize mental health and well-being in their own lives and communities. Our ultimate goal is to build a network of interconnected individuals and groups who are committed to creating a more compassionate, understanding, and resilient world.</p>
        <p>Through our unwavering dedication to holistic care and community support, we aim to be a beacon of hope and healing for all who seek it. Our vision is to create a lasting legacy of wellness and connection that empowers individuals and strengthens the fabric of our society.</p>

        <h2>What We Believe</h2>
        <p>Mental health encompasses emotional, psychological, and social well-being. It influences cognition, perception, and behaviour, as well as determines how an individual handles stress, interpersonal relationships, and decision-making.</p>
        <p>Our vision is to provide culturally adaptive, holistic, and wellness focused services that promote social-emotional development, prevent mental health challenges, and address the ongoing social-emotional problems.</p>
        <p>We believe in improving the community’s understanding of synergy between mental and physical health, leading to improved mind-body connection. Provide education and opportunities for individuals to identify early warning signs of mental illness and subsequently provide programs and an environment that supports recovery and improves resilience for these individuals.</p>
        <p>Maintaining client confidentiality is our top priority. We believe that people needing mental health help and treatment should be confident that their information remains confidential so that they can without hesitation avail our care to have a better life.</p>
        <p>We strongly promote the advocacy for improved psychological support and treatment particularly at the district, state, and country levels, wherever reform is needed.</p>
        <p>Each human being, irrespective of disability, race, ethnicity, gender, age, economic status, or sexual orientation, has the right to live with honour and equality, the right to be treated with compassion, respect, and dignity, free from stigma and prejudice.</p>
        <p>Mental health is essential for personal well-being, and is fundamental to achieving a healthy, balanced, and productive life. Appropriate and timely treatment process offers a powerful psychological return on the time and money invested. With the help of modern treatment methodologies, what was only a hope in the past is quickly becoming a realistic cure. We persistently advocate for treatment and services for those who need them.</p>
        <p>My forte is providing psychological aid in a clinical setup. I take every opportunity to educate people and encourage them to share their struggles with mental illness. I find that when people understand the true facts of what a mental illness is, they will think twice about making comments. I also remind them that they wouldn't make fun of someone with diabetes, heart disease, or cancer.</p>
        <p>Since most of our population is struggling with mental illness, the simple act of showing affection can make their day and also remind others of something so easily forgotten: the humanity of those who are suffering.</p>
        <p>Every day, in every possible way, I help people stand up to stigma. I strongly believe in this, and for me, it is very important to provide a welcoming and positive environment, away from labels towards a holistic approach to betterment.</p>
        <p>Most people who live with mental illness have, at some point, been blamed for their condition. They have been called names. Their symptoms have been referred to as “a phase” or something they can control “if they only tried.” They have been illegally discriminated against, with no justice. This is the unwieldy power that stigma holds.</p>
        <p>Stigma causes people to feel ashamed for something that is out of their control. Worst of all, stigma prevents people from seeking the help they need. Stigma is an unacceptable addition to their pain and their already heavy burden. And while stigma has reduced in recent years, the pace of progress has not been quick enough.</p>
        <p>Mental health issues have been a silent battle for many with the whole stigma around it and the immense fear of labelling people are often discouraged to share their emotions, thoughts, and feelings.</p>
        <p>Working as a psychologist has been my lifelong calling, and I have been practicing for more than a decade and helped a wide variety of patients improve their lives by teaching them effective coping techniques and helping them to change their behavioural patterns. Follow-up studies showed that 87% of these patients noticed a significant improvement in their mental health and overall well-being. I have always enjoyed interacting with each patient and learning how I can help them face daily challenges.</p>
        <p>My passion for working in this field inspired me to be closely associated with places like Cancer Institute, Chennai and Tata Cancer Institute, Kolkata. I participated in multiple studies on depression, substance abuse, and psycho oncology. One of the experiments focused on alleviating the signs of depression and improving a patient’s overall well-being. This study provided valuable information to researchers, and 73% of participants felt an improvement in their symptoms. Overall, this study was vital in helping doctors create additional guidelines for patients that suffer from this disorder.</p>
        <p>For me, the concept of mental health doesn’t end with diagnosis and recovery. It’s vital to focus on maintenance as well. We all have certain levels of anxiety within us, to manage the levels, we need to focus on the source rather than the trigger, so when we ask a loved one what they’re feeling, people will be more acceptable towards their mental health and that of others. My goal is to make mental health more accessible. I am working as someone who would like to address the issues not only at a symptomatic manner but focus on the asymptomatic details. Uncovering the underlying beliefs and emotions within humans is important, and my way of working includes a holistic approach to betterment.</p>
        <p>Pandemic was a huge transition for everyone, a paradigm shift. Like any other transition, it brought in uncertainty, lack of vision, unpredictability, and lack of insight. This furthermore led to multiple associations which catapulted anxiety and fear.</p>
        <p>The best thing is to pace yourself during a transition. “Slow down to speed up.” You’ve heard this which will help to create a homeostasis.</p>
        <p>Transition management does not mean that an immediate return to normal will be possible. Instead, the transition process will take place in accordance with a phased approach whereby society, systems, and services are gradually re-opened, potentially in new forms. Each phase may involve adjustments to restrictions and potential re-employment of previous stricter measures. During this complex process, if people think that they are or soon will be returning to normal, their actions may hasten the onset of a psychological breakdown, so scheduling and creating smaller goals will help them feel more secured and help in better adaptation towards the new lifestyle.</p>
        <p>There has always been a judgement about how people feel as feelings and emotions have always been abstract. We always have a specific diet plan for our tummy when upset, why can’t we have a similar plan for the mind? I have been practising as a mental health professional for quite some time and I consider myself to be the lucky few who wake up every morning to look forward to work. It pains me to see that the evolution of mental care is still at a very nascent stage. All it needs is compassion and tolerance towards each other. How often do we ask the person beside us, “How are you feeling today?” UNDERSTANDING AIN’T NO UNDERSTATEMENT. But how do we do it if people are still not aware of their own feeling, how do we make someone else talk about it? This thought travelled my mind for a long time and all I ever wanted was to simplify the whole concept of awareness. That’s how House of Calm came to my mind. Evolve is the earliest word of existence and atypical to our natural selection. We survived and outsmarted the Neanderthals only with respect to our mental capacity, then why not get more aware of it and be more evolved. With this vision, I see myself creating a global platform wherein people are more aware of themselves, their feelings and are able to talk freely about their mental health and own it with pride.</p>
      </div>
    </div>
  );
};

export default OverallInfo;
